[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "splrand"
authors = [{name = "Matteo Brini, Chiara Tomaiuolo"}]
dynamic = ["version", "description"]
